# Remap prefix to Ctrl-a
set -g prefix C-a

# Bind Ctrl-a Ctrl-a to Ctrl-a
bind C-a send-prefix
unbind C-b


# Set Vi mode for navigation and selection
set w -b mode-keys vi
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-selection
